project:
  type: website
  output-dir: docs
website:
  page-navigation: true
  back-to-top-navigation: true
  title: Intermediate R course
  navbar:
    left:
    - href: index.qmd
      text: Home
    - about.qmd
  sidebar:
    contents: auto
format:
  html:
    theme: cosmo
    css:
    - styles.css
    - include/webex.css
    toc: true
    include-after-body: include/webex.js
